# Cross-language conformance: a .cytome WRITTEN by Python cytome must be read by cytome (native R)
# bit-for-bit. The fixture (inst/extdata/reference.cytome + expected_*.csv) is generated by
# tools/make_reference_cytome.py. RNA uses zstd, ATAC uses lz4 — so both codecs are exercised.

ext <- function(f) system.file("extdata", f, package = "cytome")
ref <- ext("reference.cytome")

test_that("fixture is present", {
  skip_if(ref == "" || !file.exists(ref), "reference.cytome not installed")
  expect_true(file.exists(ref))
})

test_that("entity tables match Python", {
  skip_if(!file.exists(ref))
  x <- cytome_open(ref); on.exit(cytome_close(x))
  cells <- cytome_obs(x, "cells")
  exp_cells <- read.csv(ext("expected_cells.csv"), stringsAsFactors = FALSE)
  expect_equal(cells$barcode, exp_cells$barcode)
  expect_equal(as.character(cells$sample_id), as.character(exp_cells$sample_id))
  expect_equal(as.integer(cells$n_counts), as.integer(exp_cells$n_counts))
  genes <- cytome_var(x, "RNA_counts")
  exp_genes <- read.csv(ext("expected_genes.csv"), stringsAsFactors = FALSE)
  expect_equal(genes$gene_id, exp_genes$gene_id)
})

test_that("RNA matrix (zstd) matches Python exactly", {
  skip_if(!file.exists(ref))
  x <- cytome_open(ref); on.exit(cytome_close(x))
  M <- read_cytome_matrix(x, "RNA_counts")            # features x cells
  exp <- as.matrix(read.csv(ext("expected_rna.csv"), row.names = 1, check.names = FALSE))  # cells x genes
  expect_equal(dim(M), c(ncol(exp), nrow(exp)))       # genes x cells
  expect_equal(unname(as.matrix(Matrix::t(M))), unname(exp), tolerance = 1e-6)
})

test_that("ATAC matrix (lz4) matches Python exactly", {
  skip_if(!file.exists(ref))
  x <- cytome_open(ref); on.exit(cytome_close(x))
  comp <- DBI::dbGetQuery(x$con,
    "SELECT DISTINCT compression FROM matrix_chunks WHERE matrix_name='ATAC_counts'")$compression
  expect_true("lz4" %in% comp)                        # ensure we really test the lz4 codec
  M <- read_cytome_matrix(x, "ATAC_counts")
  exp <- as.matrix(read.csv(ext("expected_atac.csv"), row.names = 1, check.names = FALSE))
  expect_equal(unname(as.matrix(Matrix::t(M))), unname(exp), tolerance = 1e-6)
})

test_that("embedding matches Python", {
  skip_if(!file.exists(ref))
  x <- cytome_open(ref); on.exit(cytome_close(x))
  if (!("X_umap" %in% cytome_embeddings(x))) skip("no X_umap in fixture")
  em <- cytome_embedding(x, "X_umap")
  exp <- as.matrix(read.csv(ext("expected_umap.csv"), row.names = 1, check.names = FALSE))
  expect_equal(unname(em), unname(exp), tolerance = 1e-5)
})

test_that("streaming reduces to the same totals as the full matrix", {
  skip_if(!file.exists(ref))
  x <- cytome_open(ref); on.exit(cytome_close(x))
  M <- read_cytome_matrix(x, "RNA_counts")            # genes x cells
  full_totals <- Matrix::colSums(M)                   # per-cell totals
  per_chunk <- cytome_stream(x, "RNA_counts", function(m, s, e, i) Matrix::rowSums(m))  # cells x genes chunks
  stream_totals <- unlist(per_chunk)
  expect_equal(unname(stream_totals), unname(full_totals), tolerance = 1e-6)
})

test_that("read_cytome_sce builds a SingleCellExperiment", {
  skip_if(!file.exists(ref))
  skip_if_not_installed("SingleCellExperiment")
  sce <- read_cytome(ref)
  expect_s4_class(sce, "SingleCellExperiment")
  expect_equal(ncol(sce), 12L)
  expect_true("ATAC" %in% SingleCellExperiment::altExpNames(sce))
  expect_true("X_umap" %in% SingleCellExperiment::reducedDimNames(sce))
})

test_that("read_cytome_seurat builds a Seurat object", {
  skip_if(!file.exists(ref))
  skip_if_not_installed("SeuratObject")
  so <- read_cytome(ref, as = "Seurat")
  expect_s4_class(so, "Seurat")
  expect_equal(ncol(so), 12L)
  expect_true("ATAC" %in% SeuratObject::Assays(so))
  expect_true("X_umap" %in% SeuratObject::Reductions(so))
})
