// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cytome_decompress
RawVector cytome_decompress(RawVector blob, std::string method);
RcppExport SEXP _cytome_cytome_decompress(SEXP blobSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type blob(blobSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(cytome_decompress(blob, method));
    return rcpp_result_gen;
END_RCPP
}
// cytome_compress
RawVector cytome_compress(RawVector blob, std::string method);
RcppExport SEXP _cytome_cytome_compress(SEXP blobSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type blob(blobSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(cytome_compress(blob, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cytome_cytome_decompress", (DL_FUNC) &_cytome_cytome_decompress, 2},
    {"_cytome_cytome_compress", (DL_FUNC) &_cytome_cytome_compress, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_cytome(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
