# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cytome_decompress <- function(blob, method) {
    .Call(`_cytome_cytome_decompress`, blob, method)
}

cytome_compress <- function(blob, method) {
    .Call(`_cytome_cytome_compress`, blob, method)
}

